### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by sebastienrouif** [kitesurfer1404/photobooth#1]
Hi I know it's an old project but did you end up finishing the Raspberry Pi version ?
Thanks

**Comment by kitesurfer1404** [comment]
Not yet, but I will, because I need the booth at my sisters wedding, soon.
Keep watching. I'll probably add code for printing and selecting frames online and stuff like that.

**Comment by sebastienrouif** [comment]
If you have early stuff ready I'll be happy to help, I'm trying to have a tablet as display of the pictures after they have been taken. I could give a hand

**Comment by kitesurfer1404** [comment]
Code will hopefully released this weekend. Stay tuned. Worked like a charm on my sisters wedding. Added a little bonus: printing is now supported. :)

**Comment by sebastienrouif** [comment]
Looking forward to reading the code , I made my own in the end :)  I need to clean up the code and republish it

**Comment by kitesurfer1404** [comment]
Slideshow is now added. Documentation for RasPi setup also. And as a bonus I added the artwork.
I close this now. But I'm interested in your solution. Please share, of possible. Thanks!

**Comment by sebastienrouif** [comment]
Thanks, nice explanations :)
I've implemented this https://github.com/sebastienrouif/photoboothPi

**Comment by kitesurfer1404** [comment]
Nice implementation. I like the idea of the tablet connected via USB. Great idea using VNC as a "remote display", too. :D Cheapest way to get a big, portable, multifuntion touch-monitor for the Pi.
