### ISSUE TITLE
Inkscape vector graphic

### ISSUE THREAD

**Issue by Augustiner1328** [kitesurfer1404/photobooth#2]
Hi Kitesurfer,

i really like the Design of your photobooth - great Work!!
It would be very kind of you, if you could share the design Image too.

Best regards

**Comment by kitesurfer1404** [comment]
I have to check copyrights. Working on the RasPi code release for this weekend. Stay tuned.

**Comment by Augustiner1328** [comment]
nice - thanks a lot!

**Comment by kitesurfer1404** [comment]
Added artwork directory. SVG was made with inkscape. Please adjust all positions and sizes to your needs.
