### ISSUE TITLE
Switch off KenBurns Effect

### ISSUE THREAD

**Issue by sxwid** [kitesurfer1404/photobooth#3]
My Raspberry is lagging due to the KenBurns Effect. I am really bad in Java - is there an easy solution to get a simple image after image slideshow with no effect?

**Comment by kitesurfer1404** [comment]
Take a look at the CSS code in raspi/photobooth/slideshow/slideshow.css 
You might want to remove a lot of lines having _transform_ or _transition_ in them. I had this issue with an RasPi 2. Upgrading to 3 helped with this performance issue.

**Comment by sxwid** [comment]
I managed to do so, thanks a lot for the support!
